Php examples
EasyPost/examples pull request #11
Opened 2022-08-09 20:21 UTC by ryannguyen16

2022-08-12 21:01 UTC, jchen293 requested changes
Please remove the `venv` folder, this isn't part of this PR

2022-08-15 16:59 UTC, Justintime50 approved these changes

2022-08-15 17:14 UTC, jchen293 requested changes

2022-08-15 17:14 UTC, jchen293 commented on official/docs/php/addresses/CreateAddress.php
> +echo $addresss;
```suggestion
echo $address;
```
extra `s`

2022-08-15 17:14 UTC, jchen293 commented on official/docs/php/addresses/CreateAndVerifyAddress.php
> +echo $addresss;
```suggestion
echo $address;
```

2022-08-15 17:14 UTC, jchen293 commented on official/docs/php/addresses/RetrieveAddressList.php
> +echo $addressses;
```suggestion
echo $addresses;
```

2022-08-15 17:14 UTC, jchen293 commented on official/docs/php/addresses/StrictVerifyAddress.php
> +echo $addressses;
```suggestion
echo $address;
```

2022-08-15 17:14 UTC, jchen293 commented on official/docs/php/addresses/VerifyExistingAddress.php
> +echo $addressses;
```suggestion
echo $address;
```

2022-08-15 17:14 UTC, jchen293 commented on official/docs/php/shipments/CreateShipment.php
> +]);
missing print statement

2022-08-15 17:45 UTC, jchen293 requested changes
I noticed that we used `double quotes` and `single quotes` in some files. I see we use both `double quotes` and `single quote` in some associated arrays, and also when retrieving an object by passing either `'obj_...'` or `"obj_..."` in Object::retrieve().

2022-08-15 17:45 UTC, jchen293 commented on official/docs/php/addresses/RetrieveAddress.php
> +echo $addresss;
```suggestion
echo $address;
```

My bad, here is another one

2022-08-15 17:45 UTC, jchen293 commented on official/docs/php/addresses/StrictVerifyAddress.php
> +echo $addresses;
```suggestion
echo $address;
```

2022-08-15 17:45 UTC, jchen293 commented on official/docs/php/addresses/VerifyExistingAddress.php
> +echo $addresses;
```suggestion
echo $address;
```

2022-08-15 17:45 UTC, jchen293 commented on official/docs/php/api_keys/RetrieveApiKey.php
> +<?php
This file should be plural `RetrieveApiKeys.php`

2022-08-15 17:45 UTC, jchen293 commented on official/docs/php/shipments/InsureShipment.php
> +echo $shipment;
```suggestion
echo $purchasedShipment;
```

2022-08-15 18:08 UTC, Justintime50 commented
@jchen293 great callout. I added a rule to the PHP linter to check for double vs single quotes and fixed all occurances.

2022-08-15 18:59 UTC, nwithan8 approved these changes

2022-08-15 19:08 UTC, jchen293 approved these changes

2022-08-15 19:08 UTC, merged