Add missing API key retrieval examples
EasyPost/examples pull request #111
Opened 2023-09-28 18:25 UTC by dcaballeroc

Now that the functions are available for a next release on C# and Node libraries, add examples to get API Keys for child users for these. It also add missing example for Java library, which already has that functionality.

2023-09-29 16:18 UTC, Justintime50 requested changes
There are two inconsistencies I'd like fixed here please:

1. In some examples we retrieve the user then pass in the ID. Let's either forgo that on all examples and just pass in a fake string ID or let's retrieve the user on all the examples across languages
2. Some of the examples have comments on both retrieving all and retrieving child API keys, let's please ensure all examples have the comment on both to help distinguish each section of the example and that the wording is uniform across them all

2023-09-29 17:11 UTC, dcaballeroc commented
> There are two inconsistencies I'd like fixed here please:
> 
>     1. In some examples we retrieve the user then pass in the ID. Let's either forgo that on all examples and just pass in a fake string ID or let's retrieve the user on all the examples across languages
> 
>     2. Some of the examples have comments on both retrieving all and retrieving child API keys, let's please ensure all examples have the comment on both to help distinguish each section of the example and that the wording is uniform across them all

You're right. This is a WIP, still waiting for the method to get implemented in the Go library and for the methods to be moved to the right service on each library to continue.

2023-09-29 17:32 UTC, Justintime50 commented
Fair enough! I'll mark this as a draft until it's ready. Feel free to publish at that time.

2023-10-11 17:53 UTC, nwithan8 approved these changes

2023-10-11 17:57 UTC, Justintime50 commented on go.sum
>  github.com/EasyPost/easypost-go/v3 v3.0.0/go.mod h1:WDD0qkjwxedVKFXCcdJBz22rtRHpuxjGazgSVcTfdIw=
You'll wanna run `go mod tidy` to get rid of these lines

2023-10-11 17:57 UTC, Justintime50 commented on official/docs/php/current/api-keys/retrieve.php
>  $childUser = $client->user->retrieve('user_...');
thought: to keep this super simple, let's go for consistency and pass in strings for the IDs instead of including extra function calls that aren't directly relevant to the example

2023-10-11 17:57 UTC, Justintime50 commented on official/docs/python/current/api-keys/retrieve.py
>  child_user = client.user.retrieve("user_...")
same as above

2023-10-11 17:57 UTC, Justintime50 commented on official/docs/ruby/current/api-keys/retrieve.rb
>  child_user = client.user.retrieve('user_...')
same as above

2023-10-11 18:18 UTC, Justintime50 approved these changes
Nice work!

2023-10-11 18:19 UTC, merged