add create form code example to missing languages
EasyPost/examples pull request #12
Opened 2022-08-12 16:33 UTC by jchen293

Add create form code example to missing languages

2022-08-12 16:46 UTC, nwithan8 requested changes
Is this missing the C#, Python, Java and Ruby examples as well?

2022-08-12 16:46 UTC, nwithan8 commented on official/docs/curl/shipments/create-form.sh
> +        // `type` always required
In shell, comments need to be `# comment`

2022-08-12 16:47 UTC, jchen293 commented
> Is this missing the C#, Python, Java and Ruby examples as well?

Looks like Ryan already added the code example in those four languages.

2022-08-12 16:49 UTC, nwithan8 commented
> > Is this missing the C#, Python, Java and Ruby examples as well?
> 
> Looks like Ryan already added the code example in those four languages.

So he did, my bad, was looking in the wrong directory.

2022-08-12 18:43 UTC, nwithan8 approved these changes

2022-08-13 04:21 UTC, Justintime50 requested changes

2022-08-13 04:21 UTC, Justintime50 commented on official/docs/curl/shipments/create-form.sh
> +        # all other elements differ based on form type
Issue: You cannot have comments in the middle of curl examples. Please move this to line 1

2022-08-13 04:21 UTC, Justintime50 commented on official/docs/php/shipments/CreateForm.php
> +require_once("path/to/lib/easypost.php");
Issue: All PHP files must start with `<?php` to render and run properly.

2022-08-15 16:51 UTC, jchen293 commented on official/docs/curl/shipments/create-form.sh
> +        # all other elements differ based on form type
resolved

2022-08-15 16:51 UTC, jchen293 commented on official/docs/php/shipments/CreateForm.php
> +require_once("path/to/lib/easypost.php");
resolved

2022-08-15 16:59 UTC, Justintime50 commented on official/docs/php/shipments/CreateForm.php
> +require_once("path/to/lib/easypost.php");
Please remove this line (we aren't going to include these anymore, see PHP examples PR for an example.)

2022-08-15 17:02 UTC, jchen293 commented on official/docs/php/shipments/CreateForm.php
> +require_once("path/to/lib/easypost.php");
resolved

2022-08-15 17:05 UTC, jchen293 commented on official/docs/curl/shipments/create-form.sh
> +            "barcode": "855658003251"
resolved

2022-08-15 17:14 UTC, Justintime50 reviewed
Sorry, last item - we need print statements to match all the other examples for Go and PHP

2022-08-15 17:23 UTC, Justintime50 approved these changes

2022-08-15 17:27 UTC, merged