Scripts, guide export and import child user USPS account credentials
EasyPost/examples pull request #20
Opened 2022-08-31 20:54 UTC by nwithan8

2022-08-31 22:43 UTC, Justintime50 submitted a review, later dismissed
This is great! We'll need to make a few changes but this is on the right path.

2022-09-01 18:28 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +def process_child(child: easypost.User) -> dict:
Resolved

2022-09-01 18:28 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +def write_to_csv(data: List[dict]):
Resolved

2022-09-01 18:28 UTC, nwithan8 commented on official/guides/child_account_update/import.py
> +def process_entry(entry: dict, child: easypost.User):
Resolved

2022-09-01 18:28 UTC, nwithan8 commented on official/guides/child_account_update/import.py
> +def read_from_csv() -> List[dict]:
Resolved

2022-09-01 18:29 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +    }
Resolved

2022-09-01 18:31 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +        if account:
Resolved

2022-09-01 18:32 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +        'shipper_id': credential.get('shipper_id'),
Resolved

2022-09-01 18:32 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +        fieldnames = ['child_id', 'ca_id', 'credential_type', 'city', 'state', 'street', 'zip', 'company', 'email',
Resolved

2022-09-01 18:37 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +                write_entry_to_csv(credential, child['id'], writer)
Resolved.

More info: https://zetcode.com/python/csv/#:~:text=The%20writerow%20method%20writes%20a%20row%20of%20data%20into%20the%20specified%20file.&text=It%20is%20possible%20to%20write,rows%20to%20the%20CSV%20file.&text=The%20code%20example%20writes%20three,file%20using%20the%20writerows%20method.

2022-09-01 18:37 UTC, nwithan8 commented on official/guides/child_account_update/import.py
> +        process_entry(entry, matching_child)
Per our internal discussion, this is not currently feasible. Will note in the script.

2022-09-06 18:24 UTC, nwithan8 commented
@Justintime50 I still need your help to test this, since my personal account is borked.

2022-09-06 19:39 UTC, Justintime50 commented on official/guides/child_account_update/README.md
> +These scripts are intended to provide easy-to-use functionality for retrieving and updating the UspsAccount carrier credentials for each Child User linked to a Parent account.
Please add a title

2022-09-06 19:39 UTC, Justintime50 commented on official/guides/child_account_update/README.md
> +**Please note**, due to how the EasyPost client library handles switching between different API keys, these scripts may take a while to run if you have a large number of Child Users.
Please also note that these scripts are not thread safe out of the box.

2022-09-06 19:39 UTC, Justintime50 commented on official/guides/child_account_update/README.md
> +After completing [Step 1](#step-1-exportpy), you have several options to ensure accurate credential data. You can open the .CSV using your preferred editor and manually validate and update the detail
Please fix all the markdown links here since they changed.

```suggestion
After completing [Step 1](#step-1-run-the-exportpy-script), you have several options to ensure accurate credential data. You can open the .CSV using your preferred editor and manually validate and update the details for each row. Alternatively, you could programmatically update this information using your own records. As long as the data is accurate and format stays unmodified, you're ready to proceed to [Step 3](#step-3-importpy)!
```

2022-09-06 19:39 UTC, Justintime50 commented on official/guides/child_account_update/README.md
> +To run the script: `python3 import.py -k <EASYPOST_PROD_API_KEY>`
I'd add one final "conclusion" section here stating they're good to start shipping with EndShipper and point to the normal endshipper docs?

2022-09-06 19:39 UTC, Justintime50 commented on official/guides/child_account_update/export.py
> +def get_production_key(keys: List) -> Union[str, None]:
Nit: List should say what it's a list of

2022-09-06 19:39 UTC, Justintime50 commented on official/guides/child_account_update/export.py
> +def process_child(child: easypost.User) -> Dict:
Same with `Dict`, dict of what?

2022-09-06 19:39 UTC, Justintime50 commented on official/guides/child_account_update/export.py
> +    return {"id": child.id, "accounts": credentials}
Clarity is always good

```suggestion
    return {"id": child.id, "usps_accounts": credentials}
```

2022-09-06 19:39 UTC, Justintime50 commented on official/guides/child_account_update/export.py
> +            for credential in child["accounts"]:
`account` is probably a better word here since user's could have multiple USPS accounts

```suggestion
            for account in child["usps_accounts"]:
```

2022-09-06 19:39 UTC, Justintime50 commented on official/guides/child_account_update/export.py
> +    accounts = get_usps_accounts()
```suggestion
    carrier_accounts = get_usps_accounts()
```

2022-09-06 19:39 UTC, Justintime50 commented on official/guides/child_account_update/export.py
> +    for key, value in credentials.items():
At the least, this needs to be `to_dict` and we should probably remove this entirely if not needed.

```suggestion
    for key, value in credentials.to_dict().items():
```

2022-09-06 20:03 UTC, nwithan8 commented on official/guides/child_account_update/README.md
> +These scripts are intended to provide easy-to-use functionality for retrieving and updating the UspsAccount carrier credentials for each Child User linked to a Parent account.
Resolved

2022-09-06 20:04 UTC, nwithan8 commented on official/guides/child_account_update/README.md
> +**Please note**, due to how the EasyPost client library handles switching between different API keys, these scripts may take a while to run if you have a large number of Child Users.
Resolved

2022-09-06 20:05 UTC, nwithan8 commented on official/guides/child_account_update/README.md
> +After completing [Step 1](#step-1-exportpy), you have several options to ensure accurate credential data. You can open the .CSV using your preferred editor and manually validate and update the detail
Resolved

2022-09-06 20:07 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +def get_production_key(keys: List) -> Union[str, None]:
Resolved

2022-09-06 20:07 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +def process_child(child: easypost.User) -> Dict:
Resolved

2022-09-06 20:08 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +    return {"id": child.id, "accounts": credentials}
Resolved

2022-09-06 20:08 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +            for credential in child["accounts"]:
Resolved

2022-09-06 20:08 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +    accounts = get_usps_accounts()
Resolved

2022-09-06 20:09 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +    for key, value in credentials.items():
Resolved

2022-09-06 20:22 UTC, nwithan8 commented on official/guides/child_account_update/README.md
> +To run the script: `python3 import.py -k <EASYPOST_PROD_API_KEY>`
Resolved

2022-09-06 20:29 UTC, Justintime50 commented
Please also add a description to this PR since we'll have others looking at it in the future I'm sure.

2022-09-07 00:02 UTC, Justintime50 submitted a review, later dismissed

2022-09-07 00:02 UTC, Justintime50 commented on official/guides/child_account_update/export.py
> +colorama.init()
@nwithan8 we chatted about no extra dependencies 😉 This should remain a simple script with minimal setup from the user.

2022-09-07 18:43 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +colorama.init()
Resolved.

2022-09-07 18:44 UTC, nwithan8 commented on official/guides/child_account_update/import.py
> +        account.save()
Already present

2022-09-07 18:44 UTC, nwithan8 commented on official/guides/child_account_update/import.py
> +            print(f'Missing required field {k} for carrier account {row["carrier_account_id"]}')
Resolved

2022-09-07 18:45 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +        writer.writerows(rows)
Resolved

2022-09-07 18:46 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +            usps_accounts.append(account)
Resolved

2022-09-07 18:46 UTC, nwithan8 commented on official/guides/child_account_update/import.py
> +parser.add_argument("-k", "--key", required=True, help="Parent production API key")
Resolved

2022-09-07 19:06 UTC, Justintime50 requested changes

2022-09-07 19:06 UTC, Justintime50 commented on official/guides/child_account_update/export.py
> +        print(f"Processing child {count}/{total}...")
Issue: This `count` will always be `1` as it's never incremented.

2022-09-07 19:06 UTC, Justintime50 commented on official/guides/child_account_update/import.py
> +        print(f"Processing entry {count}/{total}...")
Issue: This `count` will always be `1` as it's never incremented.

2022-09-07 19:06 UTC, Justintime50 commented on official/guides/child_account_update/requirements.txt
> +colorama==0.4.5
Issue: Remove `colorama` here.

2022-09-07 20:06 UTC, nwithan8 commented on official/guides/child_account_update/import.py
> +        print(f"Processing entry {count}/{total}...")
Good catch, resolved

2022-09-07 20:06 UTC, nwithan8 commented on official/guides/child_account_update/export.py
> +        print(f"Processing child {count}/{total}...")
Good catch, resolved

2022-09-07 20:06 UTC, nwithan8 commented on official/guides/child_account_update/requirements.txt
> +colorama==0.4.5
Resolved

2022-09-07 20:10 UTC, Justintime50 approved these changes

2022-09-08 17:35 UTC, Justintime50 commented
@nwithan8 looks like prettier doesn't like your changes to the README

2022-09-08 22:37 UTC, jchen293 approved these changes

2022-09-08 22:40 UTC, merged