Update C# examples
EasyPost/examples pull request #25
Opened 2022-09-02 23:32 UTC by nwithan8

- All C# examples are (mostly) copy-paste (user will need to create an `EasyPostExamples` project to copy files into)
- Fix some bad syntax and broken tests (non-await, wrong function). We should have caught this during the initial push of these examples to the repo, oops.

2022-09-07 16:17 UTC, Justintime50 requested changes

2022-09-07 16:17 UTC, Justintime50 commented on official/docs/csharp/addresses/create-address.cs
> +        string apiKey = Environment.GetEnvironmentVariable("EASYPOST_API_KEY")!;
What does the `!` do for all these env vars?

2022-09-07 16:17 UTC, Justintime50 commented on official/docs/curl/carrier_accounts/retrieve-carrier-accounts.sh
> +curl -X GET https://api.easypost.com/v2/carrier_accounts?page_size=5 \
Please revert this particular file. The `carrier_accounts` endpoint is unpaginated so it cannot filter on page size.

2022-09-07 16:17 UTC, Justintime50 commented on official/docs/csharp/addresses/create-address.cs
> +        new TestOutputHelper().WriteLine(JsonConvert.SerializeObject(address, Formatting.Indented));
I have no idea what or where this `TestOutputHelper` is defined. Let's not use whatever it is and instead simply use the most vanilla approach (that we previously had) to printing out to console.

This is true for every example.

2022-09-07 16:17 UTC, Justintime50 commented on official/docs/csharp/batches/add-shipments-to-batch.cs
> +        );
Issue: For this to work, it needs to be a list of dictionaries that contain `id` as the key and then then the shipment ID as the value, see other libs for an example.

2022-09-07 16:17 UTC, Justintime50 commented on official/docs/csharp/batches/create-batch.cs
> +                }
Issue: For this to work, it needs to be a list of dictionaries that contain `id` as the key and then then the shipment ID as the value, see other libs for an example.

2022-09-07 16:17 UTC, Justintime50 commented on official/docs/csharp/batches/remove-shipments-from-batch.cs
> +            }
Issue: For this to work, it needs to be a list of dictionaries that contain `id` as the key and then then the shipment ID as the value, see other libs for an example.

2022-09-07 16:17 UTC, Justintime50 commented on official/docs/csharp/carrier_accounts/create-carrier-account.cs
> +                "credentials", new Dictionary<string, object>
Issue: This example should include `test_credentials` too. I'm noticing now that the curl example is missing this too. Feel free to add to that one as well.

2022-09-07 16:17 UTC, Justintime50 commented on official/docs/csharp/events/retrieve-event.cs
> +    [Fact]
Question: As I'm looking through all these, aren't the `Fact` bits only for unit tests? Do we need them here? If not, let's remove all of them from each example.

2022-09-07 16:17 UTC, Justintime50 commented on official/docs/csharp/insurances/create-insurance.cs
> +
Nit: Extra line not needed

2022-09-07 16:17 UTC, Justintime50 commented on official/docs/csharp/reports/create-report.cs
> +
Nit: extra line not needed

2022-09-07 16:17 UTC, Justintime50 commented on official/docs/csharp/scan_forms/retrieve-scanforms.cs
> +
Nit: extra line

2022-09-07 18:24 UTC, nwithan8 commented on official/docs/curl/carrier_accounts/retrieve-carrier-accounts.sh
> +curl -X GET https://api.easypost.com/v2/carrier_accounts?page_size=5 \
Resolved.

2022-09-07 18:25 UTC, nwithan8 commented on official/docs/csharp/addresses/create-address.cs
> +        new TestOutputHelper().WriteLine(JsonConvert.SerializeObject(address, Formatting.Indented));
XUnit doesn't like users printing to console:
<img width="604" alt="image" src="https://user-images.githubusercontent.com/17054780/188951221-39ee1aac-1f11-4765-a4bb-01e0a2b3d5a8.png">

2022-09-07 18:27 UTC, nwithan8 commented on official/docs/csharp/batches/add-shipments-to-batch.cs
> +        );
Actually, the add/remove shipments function in C# takes a list of Shipment objects or a list of shipment IDs directly

<img width="354" alt="image" src="https://user-images.githubusercontent.com/17054780/188951609-51fb2a98-deff-4382-bde0-6c5ae20f69c0.png">

2022-09-07 18:27 UTC, nwithan8 commented on official/docs/csharp/batches/remove-shipments-from-batch.cs
> +            }
See comment above.

2022-09-07 18:31 UTC, nwithan8 commented on official/docs/csharp/events/retrieve-event.cs
> +    [Fact]
Correct, the `Fact` attribute marks these functions as unit tests, allowing those using an IDE to simply execute a single standalone function.

We could instead make each function the `Main` function entrypoint of the program, but we'd have to [do some trickery](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.1/async-main) to get it to be asynchronous, which it needs to be for API calls.

2022-09-07 18:33 UTC, nwithan8 commented on official/docs/csharp/reports/create-report.cs
> +
Resolved

2022-09-07 18:33 UTC, nwithan8 commented on official/docs/csharp/scan_forms/retrieve-scanforms.cs
> +
Resolved

2022-09-07 18:34 UTC, Justintime50 commented on official/docs/csharp/addresses/create-address.cs
> +        new TestOutputHelper().WriteLine(JsonConvert.SerializeObject(address, Formatting.Indented));
But... these aren't unit tests. These are just example snippets

2022-09-07 18:36 UTC, Justintime50 commented on official/docs/csharp/events/retrieve-event.cs
> +    [Fact]
Let's go the `Main` entrypoint route.

2022-09-07 18:36 UTC, nwithan8 commented on official/docs/csharp/batches/create-batch.cs
> +                }
Resolved

2022-09-07 18:38 UTC, nwithan8 commented on official/docs/csharp/carrier_accounts/create-carrier-account.cs
> +                "credentials", new Dictionary<string, object>
Resolved

2022-09-07 21:29 UTC, nwithan8 commented on official/docs/csharp/addresses/create-address.cs
> +        new TestOutputHelper().WriteLine(JsonConvert.SerializeObject(address, Formatting.Indented));
Resolved in rework

2022-09-07 21:29 UTC, nwithan8 commented on official/docs/csharp/events/retrieve-event.cs
> +    [Fact]
Resolved in rework

2022-09-07 22:11 UTC, Justintime50 commented on official/docs/csharp/batches/add-shipments-to-batch.cs
> +                }
Issue: This still needs to be key/pair with an `id`.

2022-09-07 22:11 UTC, Justintime50 commented on official/docs/csharp/batches/remove-shipments-from-batch.cs
> +                }
Issue: This still needs to be key/pair with an `id`.

2022-09-07 22:30 UTC, jchen293 reviewed
@Justintime50 @nwithan8 Should we consider compressing the format for the dictionary? Some files have more than 100+ lines of code and it would make the code example really long in the API doc

2022-09-07 22:30 UTC, jchen293 commented on official/docs/csharp/carrier_accounts/update-carrier-account.cs
> +                {
```suggestion
                "credentials", new Dictionary<string, object>()
                {
```

2022-09-07 22:30 UTC, jchen293 commented on official/docs/csharp/carrier_accounts/update-carrier-account.cs
> +                {
Nit

2022-09-07 22:30 UTC, jchen293 commented on official/docs/csharp/pickups/create-pickup.cs
> +                    "max_datetime", "2022-10-01 17:30:00"
```suggestion
                    "max_datetime", "2022-10-02 10:30:00"
```
should be the next day, to be consistent with other languages code example

2022-09-07 22:30 UTC, jchen293 commented on official/docs/csharp/reports/retrieve-reports.cs
> +                }
We don't need this in the example

2022-09-07 22:30 UTC, jchen293 commented on official/docs/csharp/shipments/one-call-buy-shipment.cs
> +                {
```suggestion
                "carrier_accounts", new List<string>()
                {
```
nit

2022-09-07 22:53 UTC, nwithan8 commented on official/docs/csharp/batches/remove-shipments-from-batch.cs
> +                }
https://github.com/EasyPost/examples/pull/25#discussion_r965153037

2022-09-07 22:53 UTC, nwithan8 commented on official/docs/csharp/batches/add-shipments-to-batch.cs
> +                }
https://github.com/EasyPost/examples/pull/25#discussion_r965153037

2022-09-07 22:55 UTC, nwithan8 commented
> @Justintime50 @nwithan8 Should we consider compressing the format for the dictionary? Some files have more than 100+ lines of code and it would make the code example really long in the API doc

It's our styleguide doing that, I'm open to the idea of changing it.

2022-09-08 20:35 UTC, Justintime50 approved these changes
Looks SO much better, thank you!

2022-09-08 20:39 UTC, nwithan8 commented on official/docs/csharp/customs_info/create-customs-info.cs
> +                "NOEEI 30.37(a)"
Not sure what happened here.

2022-09-08 22:10 UTC, jchen293 reviewed
Why are some files' dictionaries not compressed?

2022-09-08 22:10 UTC, jchen293 commented on official/docs/csharp/orders/create-order.cs
> +using System;
should we compress this file? its' 60+ lines of code

2022-09-08 22:10 UTC, jchen293 commented on official/docs/csharp/orders/one-call-buy-order.cs
> +using System;
this file too, it's 70+ lines of code

2022-09-08 22:14 UTC, nwithan8 commented on official/docs/csharp/orders/one-call-buy-order.cs
> +using System;
This is as compressed as it can be. The `new` keyword unfortunately triggers a new line for the initialization of a new dictionary/list.

2022-09-08 22:14 UTC, nwithan8 commented on official/docs/csharp/orders/create-order.cs
> +using System;
This is as compressed as it can be. The `new` keyword unfortunately triggers a new line for the initialization of a new dictionary/list.

2022-09-08 22:18 UTC, jchen293 approved these changes

2022-09-08 22:31 UTC, merged