added examples
EasyPost/examples pull request #3
Opened 2022-07-18 20:01 UTC by ryannguyen16

added ruby examples

2022-07-18 20:12 UTC, Justintime50 requested changes
I'm going to add the linter for Ruby in this PR. Talked to @ryannguyen16 about it.

2022-07-18 20:12 UTC, Justintime50 commented on official/docs/C#/ApiKeys/retrieveApiKey.cs
> +using EasyPost;
It looks like a C# example is still here and shouldn't be.

2022-07-18 20:46 UTC, Justintime50 requested changes
1. I added a lint rule to ignore the need to have `# frozen_string_literal: true` in our code snippets. You would want these in a real project but since these are just snippets, let's remove them to clean up the examples a bit. You will need to remove them from every file except the `examples.gemspec` file.
2. There are still a bunch of examples missing from this PR. The number of files added should be closer to `100` not counting the ones I added for linting config. You can either double check which examples are in the `curl` subdirectory or look at all the examples in our [Postman collection](https://www.postman.com/easypost-api/workspace/easypost-api/documentation/11274540-3f58cfa3-ca23-4a58-a646-9e86b8f7178e) as they should 1:1 match the params and also the examples that are available.

Let me know if you have questions on this. Happy to pair with you too if desired.

2022-07-19 21:17 UTC, jchen293 requested changes

2022-07-19 21:17 UTC, jchen293 commented on official/docs/ruby/billing/add_bank_account.rb
> +require 'easypost'
this filename should be renamed, we are not adding a bank account to the billing, instead, we are adding funds to the wallet by using a primary or secondary method.

2022-07-19 21:17 UTC, jchen293 commented on official/docs/ruby/billing/add_credit_card.rb
> +credit_card = EasyPost::CreditCard.fund('2000', 'primary')
CreditCard class no longer exists as we have changed the design for Billing, this file should be removed.

2022-07-19 21:17 UTC, jchen293 commented on official/docs/ruby/billing/delete_credit_card.rb
> +deleted_credit_card = EasyPost::CreditCard.delete('card_...')
CreditCard class no longer exists as we have changed the design for Billing, this file should be removed.

2022-07-19 21:17 UTC, jchen293 commented on official/docs/ruby/billing/retrieve_payment_methods.rb
> +payment_methods = EasyPost::PaymentMethod.all
```suggestion
payment_methods = EasyPost::Billing.retrieve_payment_methods
```

2022-07-20 17:56 UTC, Justintime50 requested changes

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/batches/create_label_for_batch.rb
> +  { file_format: 'epl2' },
```suggestion
  { file_format: 'PDF' },
```

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/batches/manifest_batch.rb
> +batch.create_scan_form
Nit: Add a line break before to match the others?

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/batches/retrieve_batch_list.rb
> +batch_array = batches.batches
Although we need to break out the object key in our tests, we don't need to here for the example. Let's keep it as simple as possible and not include this line and simply put `batches`

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/carrier accounts/create_carrier_account.rb
> +require 'easypost'
Looks like all of the filenames that have two words in them need an underscore instead of a space for this whole PR (eg: `carrier accounts`)

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/carrier accounts/create_carrier_account.rb
> +    access_license_number: 'ALN',
Let's use the newer DHLECS account example params here instead of UPS

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/carrier accounts/delete_carrier_account.rb
> +carrier_account.delete
Nit: line break

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/carrier accounts/update_carrier_account.rb
> +carrier_account.save
Please use the new params for DHLECS, the params getting updated could also be moved to better show what's happening.
```suggestion
carrier_account = EasyPost::CarrierAccount.retrieve('ca_...')

carrier_account.description = 'FL Location UPS Account'
carrier_account.credentials['account_number'] = 'B2B2B2'

carrier_account.save
```

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/orders/create_order.rb
> +      { parcel: { predefined_package: 'FedExBox', weight: 17.5 } },
Let's split up JSON to one item per line

```suggestion
      { 
        parcel: { 
          predefined_package: 'FedExBox', 
          weight: 10.2
        }
      },

      { parcel: { predefined_package: 'FedExBox', weight: 17.5 } },
```

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/orders/one_call_buy_order.rb
> +    { parcel: { predefined_package: 'FedExBox', weight: 17.5 } },
One item per line

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/pickups/create_pickup.rb
> +    max_datetime: DateTime.now + 14_400,
Let's hard-code a date here instead.

Let's copy the Postman one for now

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/rates/retrieve_rate.rb
> +rate = EasyPost::Rate.retrieve('shp...')
Needs to be a rate ID instead of a shipment ID

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/reports/create_report.rb
> +
Let's double check for these comments, I know there are a few stragglers.

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/scan forms/create_scanform.rb
> +    shipments: [shipment],
```suggestion
    shipments: [{'id': 'shp_...'}],
```

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/shipments/insure_shipment.rb
> +purchased_shipment.insure(amount: 888.50)
Nit: newline

Let's do 100 insurance in the off chance someone copy/past/runs this without thinking and charges their account in prod.

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/shipments/refund_shipment.rb
> +shipment.refund
Nit: newline

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/shipments/regenerate_rate.rb
> +shipment.regenerate_rates
Nit: newline

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/shipments/retrieve_smartrate.rb
> +shipment.get_smartrates
Nit: newline

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/users/delete_user.rb
> +user.delete
Nit: newline

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/users/update_authenticated_user.rb
> +EasyPost.api_key = ENV['EASYPOST_API_KEY']
This example doesn't have any code in it. Let's add it.

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/webhooks/update_webhook.rb
> +webhook.update
We need to retrieve the webhook in this example.

2022-07-20 17:56 UTC, Justintime50 commented on official/docs/ruby/webhooks/delete_webhook.rb
> +webhook.delete
Need to retrieve the webhook to delete first

2022-07-21 16:51 UTC, jchen293 approved these changes

2022-07-21 16:51 UTC, jchen293 commented on official/docs/ruby/batches/add_shipment_to_batch.rb
> +require 'easypost'
@ryannguyen16  you still need to address this, the filename should be `add_shipments_to_batch.rb`

2022-07-21 16:53 UTC, jchen293 requested changes

2022-07-21 16:53 UTC, jchen293 commented on official/docs/ruby/address/create_and_verify_address.rb
> +address = EasyPost::Address.create_and_verify(
```suggestion
verified_address = EasyPost::Address.create_and_verify(
```

Once you fix this, the CI build should pass

2022-07-21 17:03 UTC, jchen293 approved these changes

2022-07-21 17:03 UTC, jchen293 commented on official/docs/ruby/address/create_and_verify_address.rb
> +puts address
```suggestion
verified_address = EasyPost::Address.create_and_verify(
  street1: '417 MONTGOMERY ST',
  street2: 'FLOOR 5',
  city: 'SAN FRANCISCO',
  state: 'CA',
  zip: '94104',
  country: 'US',
  company: 'EasyPost',
  phone: '415-123-4567',
)

puts verified_address
```

2022-07-22 15:32 UTC, Justintime50 commented on official/docs/ruby/address/create_and_verify_address.rb
> +puts address
We want to keep the examples as generic as possible. This will help keep them uniform across languages and reduce the mental overhead during maintenance.

For examples, we won't be using explicit variable names; however, if this were an app or service this would be a good callout.

2022-07-22 15:39 UTC, Justintime50 requested changes
Pretty close! A few last stragglers.

2022-07-22 15:39 UTC, Justintime50 commented on official/docs/ruby/address/create_and_verify_address.rb
> +  street1: '417 MONTGOMERY ST',
All of these parameters across the different Address files are actually a tad different for the purposes of verifying an address. You will want to take a look at the Postman/curl examples again as these do not match.

2022-07-22 15:39 UTC, Justintime50 commented on official/docs/ruby/address/strict_verify_address_on_create.rb
> +  verify_strict: ['delivery'],
All of these that say `['delivery']` for the verify param need to be changed to `true`, we'll update these in the curl/Postman as well.

2022-07-22 15:39 UTC, Justintime50 commented on official/docs/ruby/address/verify_address_on_verify.rb
> +require 'easypost'
This filename needs to be `verify_address_on_create`

2022-07-22 15:39 UTC, Justintime50 commented on official/docs/ruby/child_users/create_child_user.rb
> +require 'easypost'
Let's make sure the location of these files match the curl ones. These should be in the `users` folder and not a separate `child_users` folder.

2022-07-22 15:39 UTC, Justintime50 commented on official/docs/ruby/child_users/delete_child_user.rb
> +require 'easypost'
Let's make sure the location of these files match the curl ones. These should be in the users folder and not a separate `child_users` folder.

2022-07-22 15:39 UTC, Justintime50 commented on official/docs/ruby/orders/one_call_buy_order.rb
> +    { parcel: { predefined_package: 'FedExBox', weight: 17.5 } },
These still need to be on different lines

2022-07-22 15:39 UTC, Justintime50 commented on official/docs/ruby/scan_forms/create_scanform.rb
> +      { id: 'shp_...' },
These should be on different lines.

2022-07-22 17:48 UTC, Justintime50 approved these changes
Nice work! I know it's a lot of feedback and a lot of files but it'll go a long way to have them correct and uniform.

2022-07-25 17:33 UTC, nwithan8 approved these changes

2022-07-25 17:34 UTC, merged