feat: adds endshipper examples
EasyPost/examples pull request #31
Opened 2022-09-20 18:49 UTC by Justintime50

1. Adds the EndShipper examples for all languages
2. Makes a couple corrections to other examples

2022-09-20 18:55 UTC, Justintime50 commented
Go step is failing because we need to release the Go lib and bump it here so it knows about the new functions.

2022-09-22 00:49 UTC, nwithan8 approved these changes

2022-09-23 15:51 UTC, jchen293 requested changes

2022-09-23 15:51 UTC, jchen293 commented on official/docs/java/endShipper/CreateEndShipper.java
> +
missing import `HashMap`

2022-09-23 15:51 UTC, jchen293 commented on official/docs/java/endShipper/UpdateEndShipper.java
> +
Missing import `HashMap`

2022-09-23 15:51 UTC, jchen293 commented on official/docs/node/end_shipper/buy_shipment_with_endshipper.js
> +  retrievedShipment.buy('rate_...', null, false, 'es_...').then(console.log);
we should add the `retrieve lowest rate` code snippet here instead of passing `rate_...`, because Java, Go, and C# are using lowest rate

2022-09-23 15:51 UTC, jchen293 commented on official/docs/php/end_shipper/BuyShipmentWithEndShipper.php
> +    'rate'      => 'rate_...',
we should add the `retrieve lowest rate` code snippet here instead of passing `rate_...`

2022-09-23 15:51 UTC, jchen293 commented on official/docs/python/end_shipper/buy_shipment_with_endshipper.py
> +    rate="rate_...",
we should add the `retrieve lowest rate` code snippet here instead of passing `rate_...`

2022-09-23 15:51 UTC, jchen293 commented on official/docs/python/end_shipper/update_endshipper.py
> +)
We should retrieve an `EndShipper` here to stay consistent with other languages

2022-09-23 15:51 UTC, jchen293 commented on official/docs/ruby/end_shipper/buy_shipment_with_endshipper.rb
> +  rate: 'rate...',
we should add the `retrieve lowest rate` code snippet here instead of passing `rate_...`

2022-09-23 15:51 UTC, jchen293 commented on official/docs/ruby/shipments/buy_shipment.rb
> +  rate: 'rate...',
Some languages are using the `lowest rate` while others are just passing in `rate_...`. We should update them to be consistent, either using `lowest rate` or `rate_...`

2022-09-23 16:32 UTC, jchen293 approved these changes

2022-09-23 16:32 UTC, jchen293 commented on official/docs/java/endShipper/CreateEndShipper.java
> +        Map<String, Object> endShipperData = new HashMap<String, Object>();
```suggestion
        HashMap<String, Object> endShipperData = new HashMap<String, Object>();
```

This will need to be HashMap now

2022-09-23 16:32 UTC, jchen293 commented on official/docs/java/endShipper/UpdateEndShipper.java
> +        Map<String, Object> updateParams = new HashMap<String, Object>();
```suggestion
        HashMap<String, Object> updateParams = new HashMap<String, Object>();
```
This will need to be `HashMap` now

2022-09-23 21:40 UTC, merged