add referral examples
EasyPost/examples pull request #37
Opened 2022-10-07 20:52 UTC by jchen293

Add partner white label code examples for every language

2022-10-07 21:15 UTC, Justintime50 requested changes

2022-10-07 21:15 UTC, Justintime50 commented on official/docs/csharp/referral/update-referral-user.cs
> +            );
Sorry, I may have misspoken. When I said retrieve I meant you can just retrieve a single user. Referral Customers are just `User` objects. So let's switch this to retrieving a single user via ID instead of the whole list. This is true for all the update referral user email examples. The file names should also say `update-referral-user-email` because that's the only thing this endpoint does.

2022-10-07 21:15 UTC, Justintime50 commented on official/docs/go/referral/create-referral-user.go
> +	)
No need for extra lines, just place the values inline.

```suggestion
	referralUser, _ := client.CreateReferralCustomer(
		&easypost.UserOptions{
			Name:  "Test Referral",
			Email: "test@example.com",
			Phone: "5555555555",
		},
	)
```

2022-10-11 14:53 UTC, jchen293 commented on official/docs/go/referral/create-referral-user.go
> +	)
The values in the `UserOptions` are pointers, we can't pass in values directly, we need to dereference them. 

Link to the code: https://github.com/EasyPost/easypost-go/blob/master/user.go#L25-L37

2022-10-11 15:03 UTC, jchen293 commented on official/docs/csharp/referral/update-referral-user.cs
> +            );
Actually, we don't even need to retrieve the `User` object first, because the `update email` functions in all seven libraries are static, we can just pass in the `id` and `new email` directly to the function, the step of retrieving the `User` object and then grabbing the `id` from the object itself is redundant.

2022-10-11 16:00 UTC, nwithan8 approved these changes

2022-10-11 16:12 UTC, Justintime50 commented on official/docs/csharp/referral/update-referral-user.cs
> +            );
Great catch!

2022-10-11 16:19 UTC, merged