added java examples
EasyPost/examples pull request #4
Opened 2022-07-18 20:07 UTC by ryannguyen16

added the java examples i have finished.

2022-07-29 18:46 UTC, nwithan8 commented
@ryannguyen16 I've added Java linting to our CI. This will check that our examples follow the [same style rules ](https://github.com/EasyPost/easypost-java/blob/master/easypost_java_style.xml)we have in our Java client library (minus a few irrelevant rules).

The CI failed because there were some linting errors, mostly unused imports and a few improperly-named variables. You can [check the run log](https://github.com/EasyPost/examples/runs/7584341671?check_suite_focus=true) to see the errors. Unfortunately, I have not yet found a auto-fix style tool for Java (outside of the one built into my IDE), so you'll have to manually fix these linting issues.

2022-07-29 20:42 UTC, nwithan8 commented
I think the merge/rebase you did wiped all the CI stuff @ryannguyen16 . We can fix it next week.

2022-08-01 16:02 UTC, Justintime50 commented
@nwithan8 can you assist in re-adding the linter?

2022-08-01 17:17 UTC, nwithan8 commented
@ryannguyen16 I re-added the linter and the Ruby snippets that had gotten removed. I believe you rebased this branch on master in the opposite direction. Things should be back to where they need to be now.

2022-08-03 19:14 UTC, Justintime50 commented
@nwithan8 when you have time, can we fix the merge conflicts for the linter targets in the Makefile?

2022-08-03 20:02 UTC, nwithan8 approved these changes

2022-08-03 20:31 UTC, jchen293 requested changes

2022-08-03 20:31 UTC, jchen293 commented on official/docs/java/carrierAccounts/DeleteCarrrierAccount.java
> +        carrier_account.delete();
```suggestion
        carrierAccount.delete();
```

2022-08-03 20:31 UTC, jchen293 commented on official/docs/java/carrierAccounts/UpdateCarrierAccount.java
> +        System.out.println(carrier_account);
```suggestion
        System.out.println(carrierAccount);
```

2022-08-03 20:31 UTC, jchen293 commented on official/docs/java/shipments/InsureShipment.java
> +        System.out.println(shipment);
```suggestion
        System.out.println(purchasedShipment);
```

2022-08-03 20:31 UTC, jchen293 commented on official/docs/java/shipments/RetrieveShipmentList.java
> +        System.out.println(shipment);
```suggestion
        System.out.println(shipments);
```

2022-08-03 20:31 UTC, jchen293 commented on official/docs/java/trackers/RetrieveTrackerList.java
> +        System.out.println(tracker);
```suggestion
        System.out.println(trackers);
```

2022-08-03 20:31 UTC, jchen293 commented on official/docs/java/users/UpdateChildUser.java
> +        System.out.println(user);
```suggestion
        System.out.println(me);
```

2022-08-03 20:31 UTC, jchen293 commented on official/docs/java/users/UpdateUser.java
> +        System.out.println(user);
```suggestion
        System.out.println(me);
```

2022-08-03 20:31 UTC, jchen293 commented on official/docs/java/webhooks/RetrieveWebhookList.java
> +        System.out.println(webhook);
```suggestion
        System.out.println(webhooks);
```

2022-08-04 18:16 UTC, Justintime50 commented
@jchen293 want to re-review please?

2022-08-05 15:59 UTC, jchen293 requested changes
very close, once you address these I will stamp

2022-08-05 15:59 UTC, jchen293 commented on official/docs/java/billing/DeletePaymentMethod.java
> +
Missing code here.

2022-08-05 15:59 UTC, jchen293 commented on official/docs/java/batches/RetrieveBatch.java
> +        Batch batch = Batch.retrieve("batch_...");
Missing print statement

2022-08-05 15:59 UTC, jchen293 commented on official/docs/java/batches/RemoveShipmentFromBatch.java
> +        batch.removeShipments(batchMap);
Missing print statement

2022-08-05 15:59 UTC, jchen293 commented on official/docs/java/insurances/RetrieveInsuranceList.java
> +        InsuranceCollection insurances = Insurance.all(list_params);
```suggestion
        InsuranceCollection insurances = Insurance.all(listParams);
```

2022-08-05 17:16 UTC, jchen293 approved these changes

2022-08-05 17:50 UTC, Justintime50 requested changes

2022-08-05 17:50 UTC, Justintime50 commented on official/docs/java/batches/RetrieveBatchList.java
> +        List<Batch> batchesList = batches.getBatches();
Let's remove this line since we just want to print out the actual batch response.

2022-08-05 17:50 UTC, Justintime50 commented on official/docs/java/addresses/CreateAddress.java
> +        EasyPost.apiKey = "<EASYPOST_API_KEY>";
We should be using environment variables on all of these please.

```suggestion
        EasyPost.apiKey = System.getenv("EASYPOST_API_KEY");
```

2022-08-05 17:50 UTC, Justintime50 commented on official/docs/java/carrierAccounts/RetrieveCarrierAccountList.java
> +        listHash.put("type", "UpsAccount");
Let's remove this, we are retrieving all carrier accounts here and the type isn't needed here.

2022-08-05 17:50 UTC, Justintime50 commented on official/docs/java/insurances/CreateInsurance.java
> +
Let's remove the 2nd line break here.

2022-08-05 17:50 UTC, Justintime50 commented on official/docs/java/trackers/CreateTracker.java
> +
Let's remove the extra line here

2022-08-05 17:50 UTC, Justintime50 commented on official/docs/java/users/UpdateChildUser.java
> +
Let's remove the extra line here

2022-08-05 18:52 UTC, Justintime50 approved these changes

2022-08-08 15:56 UTC, merged