chore: rename curl examples
EasyPost/examples pull request #43
Opened 2022-10-28 21:47 UTC by Justintime50

2022-11-01 22:04 UTC, nwithan8 approved these changes

2022-11-02 15:37 UTC, jchen293 requested changes

2022-11-02 15:37 UTC, jchen293 commented on official/docs/java/current/scan-form/create.java
> +        List<Shipment> shipments = new ArrayList<Shipment>();
Missing import statements for `List` and `ArrayList`

2022-11-02 15:37 UTC, jchen293 commented on official/docs/java/current/scan-form/create.java
> +        Map<String, Object> paramMap = new HashMap<String, Object>();
Either change `Map` to `HashMap` or import `Map` to this class

2022-11-02 15:37 UTC, jchen293 commented on official/docs/java/current/scan-form/list.java
> +        Map<String, Object> indexMap = new HashMap<String, Object>();
Something here about `Map`

2022-11-02 15:37 UTC, jchen293 commented on official/docs/php/current/carbon-offset/create.php
> +);
Missing print statement

2022-11-02 15:37 UTC, jchen293 commented on official/docs/php/current/carbon-offset/one-call-buy.php
> +);
Missing print statement

2022-11-02 20:05 UTC, merged