added C# examples
EasyPost/examples pull request #5
Opened 2022-07-18 20:27 UTC by ryannguyen16

added examples for C#

2022-07-25 21:25 UTC, Justintime50 reviewed
1. Can we always print out the result like we do with the Ruby examples? 
2. Let's make sure they are as uniform as possible with Ruby. I can see some examples differ in what the patterns are, let's take another look to make sure (eg: `StrictVerifyAddress` is printing a bunch of extra misc error pieces.
3. Let's rename the `c#` directory to `csharp` instead

2022-07-26 20:56 UTC, ryannguyen16 commented
I was unable to get my visual studio working so I didn't test if it prints the correct result yet. I will try and do that tomorrow.

2022-07-27 20:32 UTC, nwithan8 commented
Added C# linting and formatting to the CI and Makefile. Unfortunately, because of how .NET projects work, the only linting it can do with [a loose collection of `.cs` files](https://github.com/dotnet/format) (instead of an actual .NET `.csproj` project or `.sln` solution) is whitespace cleanup (spaces, indents, newlines, etc.)

2022-07-27 20:34 UTC, nwithan8 commented on Makefile
> +	# clean up whitespace formatting
**Reviewer Note**: The indention looks off here because the first line is a tab (will show up as a comment in console when running this step), while the second one is four spaces (won't show up). I purposefully did this so the first comment will appear when running this step to remind users what this step does (and does not) do.

2022-07-27 20:42 UTC, Justintime50 commented on Makefile
> +    # folder options skip looking for a project/solution, just analyze any *.cs file
Invalid indentation here @nwithan8

2022-07-27 20:42 UTC, Justintime50 commented on Makefile
> +.PHONY: help install install-csharp install-ruby lint lint-csharp lint-ruby lint-shell format format-csharp format-ruby format-shell
Editor needs to be adding newlines on save. @nwithan8

2022-07-27 21:03 UTC, nwithan8 commented on Makefile
> +    # folder options skip looking for a project/solution, just analyze any *.cs file
https://github.com/EasyPost/examples/pull/5#discussion_r931557451

2022-07-27 21:11 UTC, Justintime50 commented on Makefile
> +	# clean up whitespace formatting
I'd prefer we just `@echo` this out then if we want to give input back to the user.

2022-08-01 16:18 UTC, Justintime50 requested changes

2022-08-01 16:18 UTC, Justintime50 commented on official/docs/csharp/ApiKeys/RetrieveApiKey.cs
> +Console.Write(api_keys);
Let's replace all the write lines with this (make sure the variables stay the same!): 

```suggestion
Console.WriteLine(JsonConvert.SerializeObject(api_keys, Formatting.Indented));
```

2022-08-01 16:18 UTC, Justintime50 commented on official/docs/csharp/User/DeleteUser.cs
> +using EasyPost;
Let's remove this file

2022-08-01 16:18 UTC, Justintime50 commented on official/docs/csharp/User/UpdateUser.cs
> +using EasyPost;
Let's call this file `UpdateAuthenticatedUser` instead.

2022-08-01 16:18 UTC, Justintime50 commented on official/docs/csharp/addresses/CreateVerifiedAddress.cs
> +        { "verify", new List<booolean>() { true } }
```suggestion
        { "verify", true }
```

2022-08-01 16:18 UTC, Justintime50 commented on official/docs/csharp/addresses/StrictVerifyAddress.cs
> +        { "verify_strict", new List<booolean>() { true } }
```suggestion
        { "verify_strict", true }
```

2022-08-01 16:18 UTC, Justintime50 commented on official/docs/csharp/addresses/VerifyExistingAddress.cs
> +        { "verify_strict", new List<booolean>() { true } }
```suggestion
```

2022-08-01 16:18 UTC, Justintime50 commented on official/docs/csharp/batches/AddShipmentToBatch.cs
> +using EasyPost;
File name should be `AddShipmentsToBatch` plural

2022-08-01 16:18 UTC, Justintime50 commented on official/docs/csharp/batches/CreateBatch.cs
> +      {"id", "shp_..."}
Should have consistent spacing here

2022-08-01 16:18 UTC, Justintime50 commented on official/docs/csharp/customsInfo/CreateCustomsInfo.cs
> +        {"hs_tariff_number", "123456"},
Consistent spacing

2022-08-01 16:18 UTC, Justintime50 commented on official/docs/csharp/customsInfo/CreateCustomsInfo.cs
> +  {"eel_pfc", "NOEEI 30.37(a)"}
Consistent spacing

2022-08-01 16:18 UTC, Justintime50 commented on official/docs/csharp/trackers/RetrieveTracker.cs
> +Tracker tracker = await Tracker.Retrieve("trk_...");
Looks like we're missing the print statement

2022-08-01 18:00 UTC, Justintime50 approved these changes
Nice work! These are much cleaner than our current set.

2022-08-01 19:57 UTC, jchen293 requested changes

2022-08-01 19:57 UTC, jchen293 commented on official/docs/csharp/CarrierAccounts/DeleteCarrierAccount.cs
> +await ca.Delete();
```suggestion
await carrierAccount.Delete();
```

2022-08-01 19:57 UTC, jchen293 commented on official/docs/csharp/CarrierAccounts/RetrieveCarrierAccountList.cs
> +Console.WriteLine(JsonConvert.SerializeObject(carrierAccount, Formatting.Indented));
```suggestion
Console.WriteLine(JsonConvert.SerializeObject(carrierAccounts, Formatting.Indented));
```

2022-08-01 19:57 UTC, jchen293 commented on official/docs/csharp/CarrierAccounts/UpdateCarrierAccount.cs
> +await ca.Update(new Dictionary<string, object>() {
```suggestion
await carrierAccount.Update(new Dictionary<string, object>() {
```

2022-08-01 19:57 UTC, jchen293 commented on official/docs/csharp/addresses/CreateVerifiedAddress.cs
> +        { "verify", new List<booolean>() { true } }
this still hasn't been addressed

2022-08-01 19:57 UTC, jchen293 commented on official/docs/csharp/addresses/StrictVerifyAddress.cs
> +        { "verify_strict", new List<booolean>() { true } }
this still hasn't been addressed

2022-08-01 19:57 UTC, jchen293 commented on official/docs/csharp/addresses/VerifyExistingAddress.cs
> +        { "verify_strict", new List<booolean>() { true } }
this still hasn't been addressed

2022-08-01 19:57 UTC, jchen293 commented on official/docs/csharp/batches/RetrieveBatchList.cs
> +Console.WriteLine(JsonConvert.SerializeObject(batch, Formatting.Indented));
```suggestion
Console.WriteLine(JsonConvert.SerializeObject(batches, Formatting.Indented));
```

2022-08-01 19:57 UTC, jchen293 commented on official/docs/csharp/events/RetrieveEventList.cs
> +listParams = new Dictionary<string, object>() { "page_size", 5 };
```suggestion
Dictionary<string, object> listParams = new Dictionary<string, object>() { "page_size", 5 };
```
You need to the type before the variable name `listParams`

2022-08-01 19:57 UTC, jchen293 commented on official/docs/csharp/reports/CreateReport.cs
> +
this hasn't been addressed yet

2022-08-01 19:57 UTC, jchen293 commented on official/docs/csharp/reports/RetrieveReportList.cs
> +Console.WriteLine(JsonConvert.SerializeObject(report, Formatting.Indented));
```suggestion
Console.WriteLine(JsonConvert.SerializeObject(reportCollection, Formatting.Indented));
```

2022-08-01 19:57 UTC, jchen293 commented on official/docs/java/addresses/CreateVerifiedAddress.java
> +import com.easypost.EasyPost;
I am not sure why this Java file is in this C# PR

2022-08-02 17:11 UTC, Justintime50 commented
@jchen293 wanna take another look?

2022-08-02 17:17 UTC, nwithan8 approved these changes
Nit: If we want these to be true copy-paste examples, then each file will also need to import JsonConvert.

`using Newtonsoft.Json;`

I'm not blocking it because most likely, users won't be simply copy-pasting these code snippets and running them in a C# environment.

2022-08-02 17:21 UTC, Justintime50 commented
@nwithan8 I would expect people to copy/paste these. We'll do a second pass prior to implementation where our team blitzes each example for any stragglers like the items you mentioned. For now, I think this is a good start.

2022-08-02 17:22 UTC, jchen293 approved these changes

2022-08-02 17:30 UTC, Justintime50 approved these changes

2022-08-02 17:30 UTC, merged