Add "Add Credit Card" examples for each language
EasyPost/examples pull request #51
Opened 2022-12-08 23:15 UTC by nwithan8

New "Add Credit Card" example for each CL

2022-12-08 23:23 UTC, jchen293 commented on official/docs/java/current/billing/create-ep-credit-card.java
> +package referral;
We might need a code example for V5 as well, at least for now.

2022-12-08 23:24 UTC, nwithan8 commented on official/docs/java/current/billing/create-ep-credit-card.java
> +package referral;
@Justintime50 Thoughts? We also have the v3 of C#, didn't know if we were backporting our examples

2022-12-08 23:26 UTC, jchen293 commented on official/docs/java/current/billing/create-ep-credit-card.java
> +package referral;
I think we need one before we officially release the V6 Java

2022-12-08 23:47 UTC, Justintime50 commented on official/docs/java/current/billing/create-ep-credit-card.java
> +package referral;
Yes, these should have been there to begin with and somehow got missed so we'll need to "backport" these examples because the functionality existed in those older versions.

2022-12-09 19:01 UTC, nwithan8 commented on official/docs/java/current/billing/create-ep-credit-card.java
> +package referral;
Resolved

2022-12-09 19:27 UTC, Justintime50 requested changes

2022-12-09 19:27 UTC, Justintime50 commented on official/docs/csharp/v3/billing/create-ep-credit-card.cs
> +            PaymentMethod paymentMethod = await Partner.AddCreditCardToUser(referralUserApiKey, "0123456789101234", "01", "2028", "111", PaymentMethod.Priority.Primary);
All the params need to match the already existing Curl and Response params please, otherwise it looks goofy.

Did we use the auto-generation tool to create these? If not, this is a great first use-case to see what holes we need to fill.

2022-12-09 19:31 UTC, nwithan8 commented on official/docs/csharp/v3/billing/create-ep-credit-card.cs
> +            PaymentMethod paymentMethod = await Partner.AddCreditCardToUser(referralUserApiKey, "0123456789101234", "01", "2028", "111", PaymentMethod.Priority.Primary);
Resolved

2022-12-12 19:01 UTC, Justintime50 reviewed
The credit card number still doesn't match the responses `last4`

2022-12-12 19:11 UTC, jchen293 approved these changes

2022-12-12 19:13 UTC, Justintime50 commented
> > The credit card number still doesn't match the responses `last4`
> 
> All credit card API calls are using a Visa card, expiration 01/2025, number 0123456789101234. The only thing that does not use this is a Mastercard in the billing response that is that secondary card, and therefore a different number.

Ok, then let's update the response to match this new number. 

TLDR: I don't really care, as long as everything lines up.

2022-12-12 19:28 UTC, nwithan8 commented
> > > The credit card number still doesn't match the responses `last4`
> > 
> > 
> > All credit card API calls are using a Visa card, expiration 01/2025, number 0123456789101234. The only thing that does not use this is a Mastercard in the billing response that is that secondary card, and therefore a different number.
> 
> Ok, then let's update the response to match this new number.
> 
> TLDR: I don't really care, as long as everything lines up.

It is.

2022-12-12 19:40 UTC, Justintime50 approved these changes

2022-12-12 20:07 UTC, merged