add code snippets for Stripe connect
EasyPost/examples pull request #59
Opened 2023-01-10 20:47 UTC by jchen293

add code snippets for Stripe connect in all languages and JSON response

2023-01-10 21:09 UTC, jchen293 commented
Putting this PR in draft until we release the Gg so I can bump the Go version to make build passes

2023-01-11 17:27 UTC, nwithan8 approved these changes

2023-01-11 17:48 UTC, Justintime50 requested changes
All of these files titled `add-payment` need to be `add-payment-method`. Those are totally different.

2023-01-11 17:48 UTC, Justintime50 commented on official/docs/ruby/current/referral-customers/add-payment.rb
> +  'ba_123',
This needs `priority` param

2023-01-11 17:48 UTC, Justintime50 commented on official/docs/golang/current/referral-customers/add-payment.go
> +	paymentMethod, _ := client.BetaAddPaymentMethod("cus_123", "ba_123")
This needs `priority` param

2023-01-11 17:48 UTC, Justintime50 commented on official/docs/csharp/current/referral-customers/add-payment.cs
> +            PaymentMethod paymentMethod = await Client.Beta.Referral.AddPaymentMethod("cus_123", "ba_123");
This needs `priority` param

2023-01-11 17:50 UTC, jchen293 commented on official/docs/golang/current/referral-customers/add-payment.go
> +	paymentMethod, _ := client.BetaAddPaymentMethod("cus_123", "ba_123")
This function doesn't need the `priority` param:https://github.com/EasyPost/easypost-go/blob/master/referral.go#L190

2023-01-11 17:52 UTC, jchen293 commented on official/docs/ruby/current/referral-customers/add-payment.rb
> +  'ba_123',
Not necessary, the default param is set to `primary` in ruby: https://github.com/EasyPost/easypost-ruby/blob/master/lib/easypost/beta/referral.rb#L118

2023-01-11 17:56 UTC, Justintime50 commented on official/docs/ruby/current/referral-customers/add-payment.rb
> +  'ba_123',
This is documentation. We need to show people all their options.

2023-01-11 18:15 UTC, Justintime50 commented on official/docs/golang/current/referral-customers/add-payment.go
> +	paymentMethod, _ := client.BetaAddPaymentMethod("cus_123", "ba_123")
Please patch in the v2.11.1 version of Go and then include the priority here as well.

2023-01-11 18:25 UTC, jchen293 commented on official/docs/golang/current/referral-customers/add-payment.go
> +	paymentMethod, _ := client.BetaAddPaymentMethod("cus_123", "ba_123")
resolved

2023-01-11 18:26 UTC, jchen293 commented on official/docs/csharp/current/referral-customers/add-payment.cs
> +            PaymentMethod paymentMethod = await Client.Beta.Referral.AddPaymentMethod("cus_123", "ba_123");
added

2023-01-11 18:26 UTC, jchen293 commented on official/docs/ruby/current/referral-customers/add-payment.rb
> +  'ba_123',
added

2023-01-11 18:27 UTC, Justintime50 approved these changes
Thanks for doing this and sorry for the Go mess.

2023-01-11 18:36 UTC, merged