feat: add create carrier curl examples
EasyPost/examples pull request #62
Opened 2023-01-18 19:19 UTC by Justintime50

Adds all curl example snippets to create carrier accounts for all carriers we support.

2023-01-18 21:23 UTC, nwithan8 requested changes

2023-01-18 21:23 UTC, nwithan8 commented on official/guides/create-carrier-curls/bond.sh
> +curl -X POST https://api.easypost.com/v2/carrier_accounts \
We don't support Bond anymore.

2023-01-18 21:32 UTC, Justintime50 commented on official/guides/create-carrier-curls/bond.sh
> +curl -X POST https://api.easypost.com/v2/carrier_accounts \
hmm, deleted before I copied. Fixed

2023-01-18 21:36 UTC, jchen293 approved these changes

2023-01-20 16:54 UTC, nwithan8 approved these changes

2023-01-20 16:55 UTC, merged