adding examples
EasyPost/examples pull request #8
Opened 2022-07-29 20:43 UTC by ryannguyen16

adding half of the examples for python.

2022-08-03 20:18 UTC, nwithan8 commented
Python linter and formatter has been added to Makefile and CI.

Seems there's some linting errors present: https://github.com/EasyPost/examples/runs/7660222773?check_suite_focus=true

2022-08-08 16:47 UTC, Justintime50 requested changes
A couple of tiny things to fix, then will stamp. Nice work!

2022-08-08 16:47 UTC, Justintime50 commented on official/docs/python/addresses/verify_existing_address.py
> +address.verify()
Missing a print statement here

2022-08-08 16:47 UTC, Justintime50 commented on official/docs/python/batches/add_shipments_to_batch.py
> +batch.add_shipments(shipments=[{"id": "shp_..."}, {"id": "shp_..."}])
If we add a comma here then run `make format-python`, it will break these up on separate lines automatically.

```suggestion
batch.add_shipments(shipments=[{"id": "shp_..."}, {"id": "shp_..."},])
```

2022-08-08 16:47 UTC, Justintime50 commented on official/docs/python/events/retrieve_list_of_events.py
> +events = easypost.Events.all(page_size=5)
Missing print statement

2022-08-08 16:47 UTC, Justintime50 commented on official/docs/python/shipments/convert_label.py
> +print(shipment)
Nit: Should have a line break between the print statement and the label one above it.

2022-08-08 16:47 UTC, Justintime50 commented on official/docs/python/trackers/retrieve_tracker.py
> +
Nit: One line break instead of two

2022-08-08 18:47 UTC, Justintime50 approved these changes

2022-08-08 22:07 UTC, nwithan8 approved these changes

2022-08-08 22:07 UTC, merged

2022-08-08 22:11 UTC, jchen293 commented on official/docs/python/customs_info/create_customs_info.py
> +)
missing print statement

2022-08-08 22:11 UTC, jchen293 commented on official/docs/python/events/retrieve_event.py
> +event = easypost.Event.retrieve("evt_...")
missing print statement