add code snippets for retrieve_delivery_date function
EasyPost/examples pull request #88
Opened 2023-04-28 16:52 UTC by jchen293

2023-04-28 16:54 UTC, jchen293 commented
We will need to release Go lib first and then bump the version in this PR. Drafting this PR until we release the feature on CLs

2023-05-02 19:03 UTC, Justintime50 requested changes

2023-05-02 19:03 UTC, Justintime50 commented on official/docs/node/current/carrier-metadata/retrieve.js
> +const EasyPostBetaClient = require('@easypost/api/src/easypost');
issue: this needs to be `'@easypost/api'`, can you ensure the other beta examples for Node are corrected to this too?

2023-05-02 19:11 UTC, jchen293 commented on official/docs/node/current/carrier-metadata/retrieve.js
> +const EasyPostBetaClient = require('@easypost/api/src/easypost');
This is the only place, fixed

2023-05-02 19:12 UTC, nwithan8 approved these changes

2023-05-02 19:13 UTC, Justintime50 approved these changes
Nice work!

2023-05-02 19:14 UTC, merged