feat: v8 python code snippets
EasyPost/examples pull request #93
Opened 2023-05-19 21:11 UTC by Justintime50

2023-05-19 21:37 UTC, nwithan8 approved these changes

2023-05-19 21:41 UTC, jchen293 requested changes

2023-05-19 21:41 UTC, jchen293 commented on official/docs/python/current/api-keys/retrieve.py
>  api_keys = child_user.api_keys()
Doesn't have instance method anymore, this need to be updated

2023-05-19 21:41 UTC, jchen293 commented on official/docs/python/current/batches/add-shipments.py
> +    client.id,
```suggestion
    batch.id,
```

2023-05-19 21:41 UTC, jchen293 commented on official/docs/python/current/brand/update.py
> +updated_brand = client.user.update_brand(color="#303F9F")
need pass in `id` in the first parameter

2023-05-19 21:41 UTC, jchen293 commented on official/docs/python/current/carrier-accounts/update.py
> +updated_carrier_account = client.carrier_account.update(
need pass in `id` in the first parameter

2023-05-19 21:41 UTC, jchen293 commented on official/docs/python/current/endshipper/update.py
> +updated_end_shipper = client.end_shipper.update(
need pass in `id` in the first parameter

2023-05-19 21:41 UTC, jchen293 commented on official/docs/python/current/referral-customers/update.py
> +client.referral_customer.update_email(
need `id` in the first parameter

2023-05-19 21:41 UTC, jchen293 commented on official/docs/python/current/smartrate/retrieve-estimated-delivery-date.py
>  estimated_delivery_dates = shipment.retrieve_estimated_delivery_date(planned_ship_date="YYYY-MM-DD")
this need to be updated with client

2023-05-19 21:41 UTC, jchen293 commented on official/docs/python/current/users/update.py
> +updated_user = client.user.update(recharge_threshold="50.00")
need `id` in the first parameter

2023-05-22 04:50 UTC, jchen293 approved these changes
approving it now because i will be gone most of the days this week

2023-05-22 17:02 UTC, merged