[chore] Host style guides in examples repo
EasyPost/examples pull request #95
Opened 2023-06-05 18:27 UTC by nwithan8

This repository will become the source of truth for language-specific style guides across EasyPost.

This PR copies style guides for each client library and stores them accordingly in this repository (client libraries will then download their respective style guides from this repo during installation).

Some style guides can work generally (Ruby, .NET), while others require partially- or completely-different implementations (Go, Java suppressions, Node `.eslintrc`). Under each language in the `style_guides` folder, there are three folders: `client_library`, `examples` and `general`. General use guides and configurations go in the `general` folder, while client library- and examples-specific configurations go in their respective folders.

The client libraries will download all files from its languages's `client_library` and `general` folders, while the examples repo copies a language's `examples` and `general` folders when linting (this is handled by the individual `lint` Makefile steps in this repo)

2023-06-05 19:23 UTC, jchen293 submitted a review, later dismissed

2023-06-05 19:23 UTC, jchen293 commented on style_guides/csharp/client_library/.dummy
> +Present to ensure folder exists in git repo
Why do we need the dummy file in every language directory?

2023-06-05 19:38 UTC, nwithan8 commented on style_guides/csharp/client_library/.dummy
> +Present to ensure folder exists in git repo
To make sure the folder exists even if there's no files in it.

2023-06-06 16:15 UTC, Justintime50 requested changes
question: I'd like to investigate what will be needed to make a single styleguide for each language that works for both the examples and client libs. Are there simple adjustments we can make to each that would allow us to do so? Would clean this up a bunch and reduce complexity.

2023-06-06 16:15 UTC, Justintime50 commented on style_guides/csharp/client_library/.dummy
> +Present to ensure folder exists in git repo
I'd prefer if we don't have dummy files, and instead quiet the copy if something doesn't exist or simply don't include that copy command until it's needed. This seems kinda messy

2023-06-06 16:15 UTC, Justintime50 commented on style_guides/golang/client_library/.golangci.yml
> +  exclude: []
issue: in our go lib, we exclude `SA1019` in the Makefile, can you add that here please?

2023-06-06 16:35 UTC, nwithan8 commented
> question: I'd like to investigate what will be needed to make a single styleguide for each language that works for both the examples and client libs. Are there simple adjustments we can make to each that would allow us to do so? Would clean this up a bunch and reduce complexity.

.NET: `.editorconfig` and `layout_rules.xml` both universal, used by both (no customizations needed)
Java: `easypost_java_style.xml` universal, `style_suppressions.xml` on a per-project basis (we want to ignore certain things in our examples repo that we don't in the client library due to it being non-fully-qualified code snippets, vice versa due to a larger library)
Go: `.golangci.yml` on a per-project basis due to a wide difference of rules
Node `.prettierrc.yml` universal, `.eslintrc` on a per-project basis due to a wide difference of rules
Ruby: `easycop.yml` universal, `.rubocop.yml` only included in examples repo
PHP: `phpcs.xml` mostly universal (written for examples repo, source file path modified by a script in the client library during download)
Python: `pyproject.toml` universal, `.flake8` mostly universal (additional rule added to excluded section by a script in the client library during download)

Node and Go are really the only two that are a problem (PHP and Python handle tiny alterations in the client libraries, Java suppressions could potentially be merged together into one file)

2023-06-06 16:50 UTC, nwithan8 commented on style_guides/golang/client_library/.golangci.yml
> +  exclude: []
Resolved

2023-06-06 16:51 UTC, nwithan8 commented on style_guides/csharp/client_library/.dummy
> +Present to ensure folder exists in git repo
Resolved up to the outstanding Node and Go discussion.

2023-06-06 17:47 UTC, nwithan8 commented
Confused why Node prettier is complaining on CI, but passing end-to-end on my local machine.

2023-06-08 21:46 UTC, Justintime50 requested changes

2023-06-08 21:46 UTC, Justintime50 commented on Makefile
> +	# Install linting tool
nit: self explanatory and double verbose with the comment above, shouldn't be needed.

2023-06-08 21:46 UTC, Justintime50 commented on .gitignore
> +/.editorconfig
question: why all the slashes? gitignore should match all items without the slashes regardless of directory

2023-06-08 21:46 UTC, Justintime50 commented on Makefile
> +	cp -r style_guides/csharp/. ./
question: why not clean this up and simply have the tooling reference the config files where they are instead of spreading them all over the repo?

2023-06-08 21:46 UTC, Justintime50 commented on README.md
> +-   `community` holds code snippets contributed from the community. These may include custom workflows, how to integrate EasyPost with other software, etc
question: why the changes here?

2023-06-08 21:46 UTC, Justintime50 commented on package.json
> +    "webpack-node-externals": "^3.0.0"
issue: we don't need more than half of these here and they should definitely not get included. Much more surface area of dependencies we'll need to track. Most of these were directly for the lib (half are testing for instance) so shouldn't be included here as a blanket "catch all" to get CI to pass

2023-06-08 21:46 UTC, Justintime50 commented on style_guides/node/.babelrc
> +{
issue: babel is the compiler we use to compile our library source code down into a single JS file. This isn't needed in our examples and shouldn't be included.

2023-06-08 21:46 UTC, Justintime50 commented on style_guides/node/.eslintignore
> +types/demo
suggestion: can we copy the one used in `easypost-node`? There are additions to this file since you started this work that should be included here

2023-06-08 21:47 UTC, nwithan8 commented on .gitignore
> +/.editorconfig
We specifically only want to ignore the copies in the root, but not ignore the ones in the `style_guides` folder

2023-06-08 21:47 UTC, nwithan8 commented on Makefile
> +	cp -r style_guides/csharp/. ./
Because I don't know how to do that in most of these languages.

2023-06-08 21:47 UTC, nwithan8 commented on README.md
> +-   `community` holds code snippets contributed from the community. These may include custom workflows, how to integrate EasyPost with other software, etc
Accident.

2023-06-08 21:50 UTC, nwithan8 commented on package.json
> +    "webpack-node-externals": "^3.0.0"
I have removed all the Babel stuff. Please advise what else can be removed

2023-06-08 21:54 UTC, nwithan8 commented on package.json
> +    "webpack-node-externals": "^3.0.0"
Make steps complaining if any of the Babel stuff is removed.

2023-06-08 22:29 UTC, Justintime50 commented on Makefile
> +	cp -r style_guides/csharp/. ./
That's a pretty poor excuse 😉 A quick google search or printing the help flag on the CLI should show the config flag for each of these and could easily simplify this

2023-06-08 22:31 UTC, Justintime50 commented on package.json
> +    "webpack-node-externals": "^3.0.0"
Maybe we should meet tomorrow so I can see what it's complaining about. We shouldn't need it here.

2023-06-09 16:15 UTC, jchen293 approved these changes

2023-06-12 18:32 UTC, nwithan8 commented on Makefile
> +	cp -r style_guides/csharp/. ./
This is not possible for all languages. For example, there does not appear to be a way to specify an `.editorconfig` file for `dotnet format`, it simply uses it if it is present in the current directory.

2023-06-12 19:38 UTC, Justintime50 approved these changes
Seems fine. We'll see how this works in each repo individually

2023-06-12 19:42 UTC, merged